### PR TITLE
Add support for Animator

### PR DESCRIPTION
**Pull request by liudger**
initial support for Unity Animator #8

### CODE REVIEW

**Comment by hecomi** [comment]
Thank you for the pull request. I am currently working on organizing the animation baking mechanism and texture support, and will try to integrate the animator support code you provided after these codes are sorted out. Please give me some time.

**Comment by hecomi** [comment]
Sorry for the very late response. I have made some modifications to the code you provided and merged it. Thanks for the great PR!

**Comment by liudger** [comment]
> Sorry for the very late response. I have made some modifications to the code you provided and merged it. Thanks for the great PR!

Thanks, it needed indeed some fixes that was why I converted it too draft. I'll have a look. The code that I locally tested was working well. If needed I could make another pull request with the tweaks to reduce warnings.

**Comment by hecomi** [comment]
I have modified the code to fit the style of this project and tried to get rid of all warnings/errors I noticed.

- Ref: https://forum.unity.com/threads/after-saving-the-scene-animator-is-not-playing-an-animatorcontroller.532718/
- Change: https://github.com/hecomi/uLipSync/commit/4154939dfaafca01cbdacf27f9812fccc316de77#diff-e561548989568f46ad9bf32fe90fe2fd1babad1606f949d88249bb28604bd121R136-R143

If you notice the other bugs, I would be very happy to receive a new PR or an issue report 🙇‍♂️

**Pull request merged**
