### PR TITLE
Delta calculations

### PR DESCRIPTION
**Pull request by liudger**
Add support for Delta calculation #25. Greatly improving the accuracy for identifying the phonemes.

Interface update and new length of mfcc array
image

### CODE REVIEW

**Comment by liudger** [comment]
There are some fixes coming. Don't review yet

**Comment by liudger** [comment]
It should be good to go @hecomi

**Comment by hecomi** [comment]
Thank you for your pull request. I'm curious about the effectiveness of adding the Delta part to the MFCC. At present, we simply compare pre-acquired MFCCs with current ones using simple distance calculations or cosine similarity. With this, I'd like to investigate how much this additional 12 dimensions actually contribute to the accuracy. If it proves beneficial, I'd be keen on accepting your PR. However, if the impact is minimal, I would prefer to keep the project simple and may consider putting it on hold for the time being. I'd appreciate your thoughts on this.

**Comment by liudger** [comment]
I didn't do actual scientific test to see how much it improves. But from just using it the result looked promising. I guess we can do a comparison by using an audio file and creating sample from this file for both calculation. (it's optional the calculation) and see what is more accurate. Currently I am already on another project so this testing would be done later.

**Comment by hecomi** [comment]
Apologies for the delayed response. I have now reviewed your code.

There are changes that I would like to accept aside from the Delta calculation. It would be helpful if such changes could be provided in separate PRs in the future 🙇 

As for the Delta calculation, I am considering accepting it as an experimental feature.

Please understand that I will be modifying your contributions to fit my coding style:
- I plan to adjust some of the indentations.
- Typically, I do not add comments to the internal implementation.

Thank you for your contributions and understanding.

**Comment by hecomi** [comment]
I've read through the code, and it seems to be computing a weighted average instead of performing differentiation for the calculation of Delta MFCC. Is this code working as intended? Please correct me if I'm wrong.

https://github.com/hecomi/uLipSync/pull/44/files#diff-623438b2ee4a24923c5ba18390fed6fac4f97e80a67a1543759f696a9e715a12R508-R534

**Comment by liudger** [comment]
Let me check again the calculation  🙈

**Comment by liudger** [comment]
I'll make separate pull request for the fixes and later make a new pull request for delta MFCC's

**Pull request closed without merging**
